sonar.projectKey=rushipatel09_8.2CDevSecOps
sonar.organization=rushipatel09
sonar.host.url=https://sonarcloud.io
sonar.login=${97734e656ecd48371226e83bed498a150ac754d0}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
